# Generated by Django 4.2.7 on 2024-01-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
